# Generated by Django 4.2.11 on 2024-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='method',
            field=models.CharField(choices=[('courier', 'Кур`єр'), ('branch', 'Відділення'), ('postomat', 'Поштомат')], max_length=10),
        ),
    ]
