# Generated by Django 5.0.3 on 2024-09-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_delivery',
        ),
    ]
