# Generated by Django 5.0.3 on 2024-10-21 20:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Информація про нас',
                'verbose_name_plural': 'Информація про нас',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок слайда')),
                ('image', models.ImageField(max_length=300, upload_to='catalog/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайди',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Emeil')),
            ],
            options={
                'verbose_name': 'Контакти у верхньому меню',
                'verbose_name_plural': 'Контакти у верхньому меню',
            },
        ),
        migrations.CreateModel(
            name='PaymentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Оплата та доставка',
                'verbose_name_plural': 'Оплата та доставка',
            },
        ),
        migrations.CreateModel(
            name='ReturnAgoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Повернення товару',
                'verbose_name_plural': 'Повернення товару',
            },
        ),
        migrations.CreateModel(
            name='Safeguards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Гарантії',
                'verbose_name_plural': 'Гарантії',
            },
        ),
    ]
