# Generated by Django 5.0.3 on 2025-05-12 17:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Титул')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Информація',
                'verbose_name_plural': 'Информація',
            },
        ),
    ]
