# Generated by Django 5.0.3 on 2024-09-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайди'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='order',
        ),
    ]
