# Generated by Django 4.2.11 on 2024-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_carousel_options_remove_carousel_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Контакти у верхньому меню', 'verbose_name_plural': 'Контакти у верхньому меню'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Титул'),
        ),
        migrations.AlterField(
            model_name='paymentdelivery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Титул'),
        ),
        migrations.AlterField(
            model_name='returnagoods',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Титул'),
        ),
        migrations.AlterField(
            model_name='safeguards',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Титул'),
        ),
    ]
