# Generated by Django 5.0.3 on 2024-09-26 09:36

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Група категорій фільтрів')),
            ],
            options={
                'verbose_name': 'Група категорій фільтрів',
                'verbose_name_plural': 'Групи категорій фільтрів',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва виробника')),
                ('image', models.ImageField(max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення виробника')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
            },
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='stocks/')),
                ('title', models.CharField(max_length=100, verbose_name='Тітул')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=295, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('meta_title', models.CharField(max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Meta Description')),
                ('meta_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('seo_keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата зміни')),
                ('slug', models.SlugField(blank=True, max_length=299, null=True, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='Ліва межа')),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='Права межа')),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='ID дерева')),
                ('level', models.PositiveIntegerField(editable=False, null=True, verbose_name='Рівень')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категорія фільтрів')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.filtergroup', verbose_name='Група категорій фільтрів')),
            ],
            options={
                'verbose_name': 'Категорію фільтрів',
                'verbose_name_plural': 'Категорії фільтрів',
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значення фільтра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.filtercategory', verbose_name='Категорія фільтра')),
            ],
            options={
                'verbose_name': 'Значення фільтра',
                'verbose_name_plural': 'Значення фільтрів',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=299, unique=True, verbose_name='Назва')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('model', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Артикуль')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Кількість')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата зміни')),
                ('slug', models.SlugField(blank=True, max_length=299, null=True, verbose_name='Slug')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Знижка в %')),
                ('manufacturer', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Виробник')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукти',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення продукту')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Зображення продукту',
                'verbose_name_plural': 'Зображення продуктів',
            },
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtercategory', verbose_name='Категорія фільтра')),
                ('filter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtervalue', verbose_name='Значення фільтра')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Фільтр продукту',
                'verbose_name_plural': 'Фільтри продукту',
            },
        ),
        migrations.CreateModel(
            name='ProductToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категорія')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
