# Generated by Django 4.2.11 on 2024-09-01 08:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=295, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=255, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=299, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False, null=True)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False, null=True)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False, null=True)),
                ('level', models.PositiveIntegerField(editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория фильтра')),
            ],
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение фильтра')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.filtercategory', verbose_name='Категория фильтра')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=300, null=True, upload_to='catalog/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=299, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=299, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Скидка в %')),
                ('manufacturer', models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='stocks/')),
                ('title', models.CharField(max_length=100, verbose_name='Тітул')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
        migrations.CreateModel(
            name='StockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductToCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='stock_status_id',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to='products.stockstatus'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtercategory', verbose_name='Категория фильтра')),
                ('filter_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtervalue', verbose_name='Значение фильтра')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='products.products', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
