# Generated by Django 4.2.11 on 2024-08-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=300, null=True, upload_to='stocks/')),
                ('title', models.CharField(max_length=100, verbose_name='Тітул')),
                ('description', models.TextField(verbose_name='Опис')),
            ],
        ),
    ]
