# Generated by Django 5.0.3 on 2024-10-09 18:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
