# Generated by Django 5.0.3 on 2024-09-10 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_filtervalue_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfilter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='products.products', verbose_name='Продукт'),
        ),
    ]
