# Generated by Django 5.0.3 on 2024-09-10 17:22

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productfilter_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='filtercategory',
            options={'verbose_name': 'Категорію фільтрів', 'verbose_name_plural': 'Категорії фільтрів'},
        ),
        migrations.AlterModelOptions(
            name='filtervalue',
            options={'verbose_name': 'Значення фільтра', 'verbose_name_plural': 'Значення фільтрів'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
        migrations.AlterModelOptions(
            name='productfilter',
            options={'verbose_name': 'Фільтр продукту', 'verbose_name_plural': 'Фільтри продукту'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Зображення продукту', 'verbose_name_plural': 'Зображення продуктів'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='producttocategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата зміни'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False, null=True, verbose_name='Рівень'),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='Ліва межа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=295, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Батьківська категорія'),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='Права межа'),
        ),
        migrations.AlterField(
            model_name='category',
            name='seo_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=299, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True, verbose_name='ID дерева'),
        ),
        migrations.AlterField(
            model_name='filtercategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Категорія фільтрів'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='products.filtercategory', verbose_name='Категорія фільтра'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значення фільтра'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення виробника'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва виробника'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filter_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtercategory', verbose_name='Категорія фільтра'),
        ),
        migrations.AlterField(
            model_name='productfilter',
            name='filter_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.filtervalue', verbose_name='Значення фільтра'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення продукту'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання'),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата зміни'),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Знижка в %'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='catalog/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='products',
            name='manufacturer',
            field=models.ForeignKey(max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer', verbose_name='Виробник'),
        ),
        migrations.AlterField(
            model_name='products',
            name='model',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Артикуль'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=299, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=299, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_status_id',
            field=models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, to='products.stockstatus', verbose_name='Статус на складі'),
        ),
        migrations.AlterField(
            model_name='producttocategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='producttocategory',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Продукт'),
        ),
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
